server:
  port: 8080
  
spring:
  application:
    name: api-gateway
  cloud:    gateway:      routes:      - id: review-service
        uri: lb://REVIEW-SERVICE
        predicates:        - Path= /reviews/**
      - id: order-service
        uri: http://localhost:5565/
        predicates:        - Path= /api/v1/orders/**          

management:
  endpoints:
    web:
      exposure:
        include:
        - "*"