server:
  port: 7575
resilience4j:
  circuitbreaker:
    instances:
      reviewService:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: false
        failureRateThreshold: 10
        minimumNumberOfCalls: 3
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
        waitDurationInOpenState: 5s
        slidingWindowType: COUNT_BASED
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always

spring:
  application:
    name: review-client