spring:
  r2dbc:
    password: srivatsan
    pool:
      initial-size: 100
      max-idle-time: 30m
      max-size: 500
      validation-query: SELECT 1
    url: r2dbc:pool:mysql://127.0.0.1:3306/test
    username: root
