server:
  port: 6065

spring:
  application:
    name: rest-template-client
  
    
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      


            

